### ISSUE TITLE
Support use in typescript apps

### ISSUE THREAD

**Issue by markrickert** [4TWIGGERS/react-native-fresh-refresh#1]
I tried integrating this into a typescript app and the compiler didn't like it at all. It would be great if you could export types for those of us using strict typescript environments 👍  

This library looks like it has a lot of great potential! Thank you for publishing it!

**Comment by Mirapaghava** [comment]
Thank you ! we will export types asap.

**Comment by papidb** [comment]
Hey, I had started work on this, need some help, please check it out [here](https://github.com/papidb/react-native-fresh-refresh/blob/f522692087b2db40b631e332a18c1a74b2f84ec4/RefreshableWrapper.tsx#L21)

**Comment by papidb** [comment]
This has been resolved in https://github.com/4TWIGGERS/react-native-fresh-refresh/pull/3#issue-1089069611
