### ISSUE TITLE
Example not working.

### ISSUE THREAD

**Issue by yqz0203** [4TWIGGERS/react-native-fresh-refresh#11]
There seems something wrong with the example.

1. In order to let example run correctly, I changed the "main" field in package.json.
2. PanGesture callbacks never be fired, so onRefresh callback never be fired too. I'm not sure whether it's a problem of expo.

**Comment by alexandrius** [comment]
@yqz0203 are you using Expo 44?

**Comment by alexandrius** [comment]
Gesture Handler on Expo 44 has a bug. That’s the reason why example fails to work
