### ISSUE TITLE
weird effect when dropping the Wrapper

### ISSUE THREAD

**Issue by pmella16** [4TWIGGERS/react-native-fresh-refresh#13]
hello, I'm using the component, when I do the pull to refresh and release it, the animation is executed again making a strange effect

https://user-images.githubusercontent.com/19208317/178637033-b00b9d7b-f9e0-4fa9-9ac3-9d177ee667b7.mp4

t

**Comment by alexandrius** [comment]
Could you share the source code?

**Comment by pmella16** [comment]
> Could you share the source code?

`

const FeedScreen = ({navigation}) => {
  const AnimatedFlatlist = Animated.createAnimatedComponent(FlatList);
  
  const contentOffset = useSharedValue(0);
  const [posts, setPosts] = useState([]);
  const [loading, setLoading] = useState(true);


  const [isLoading, setIsLoading] = useState(false);
  const [listData, setListData] = useState([]);
  
  const refreshSimulationHandler = async () => {

    setIsLoading(true);    
    setPosts([]);
    const response = await fetch('api/posts');
    const data = await response.json();
  
    
    setPosts(data);
    setIsLoading(false);
  };

  useEffect(() => {
    
      const getPosts = async () => {

        const response = await fetch('api/posts');
        const data = await response.json();
        
        console.log('dataaa',data);
        
        setPosts(data);
        setLoading(false);
      }

      getPosts();

  
    }, []);
  

    const EmptyComponent = (props) => {
      return (
        <View>
          <Text>LIST EMPTY COMPONENT</Text>
        </View>
      );
    };
  
  
  
  const ListItem = ({ item }) => {
  
    console.log('item', item);
    return (
      <View style={styles.item} >
  
        <Text style={styles.itemText}>{item.category.name}</Text>
   
        { item.media.map( (e, index) => {
          return (
            
            <FastImage
            style={{ width: '100%', height: 300 }}
            source={{
              uri: e.url,
              priority: FastImage.priority.normal,
            }}
            resizeMode={FastImage.resizeMode.contain}
            key={index.toString()}
            />
            )
            
          })
        }
  
      </View>
    );
  };
  
  

  return(
  
  <>
    { loading ? 
      null
      :
<View style={styles.container}>

      <RefreshableWrapper
      contentOffset={contentOffset}
      Loader={() => <ActivityIndicator animating={true} color={Colors.red800} />}
      isLoading={isLoading}
      defaultAnimationEnabled={true}

      onRefresh={() => {
        refreshSimulationHandler();
      }}
   
      >
      <AnimatedFlatlist
        data={posts}
        keyExtractor={(item, id) => id.toString()}
        renderItem={({ item }) => {
          return <ListItem key={item.id} item={item} />;
        }}
        style={styles.scrollList}
        contentContainerStyle={styles.contenContainer}
        showsVerticalScrollIndicator={false}
        scrollEventThrottle={16}
        ListEmptyComponent={() => <EmptyComponent />}
        />
    </RefreshableWrapper>

        </View>
  }

  </>
)};


`
