### ISSUE TITLE
Horizontal ScrollView

### ISSUE THREAD

**Issue by Orange9000** [4TWIGGERS/react-native-fresh-refresh#14]
First of all, thank you for this wonderful module. This is just what I've been looking for.

Now, the problem.
I have a horizontal `ScrollView` pager with each page being a `RefreshableWrapper`.
`RefreshableWrapper` seems to be intercepting the horizontal swipe gesture, thus not allowing to scroll the pages horizontally.

I tried this: `Gesture.Exclusive(native, panGesture)`
It kinda achieves the goal but only works on android, and not ios. It also messes up horizontal/vertical scrolling experience.

Is there a way to make it work?

**Comment by Orange9000** [comment]
For anyone who may come across this, the solution is as simple as setting `minDistance` on the `panGesture`.
For example
```
Gesture.Pan()
    .minDistance(50)
    .onChange(event => {...
```

**Comment by jcoulaud** [comment]
> For anyone who may come across this, the solution is as simple as setting `minDistance` on the `panGesture`. For example
> 
> ```
> Gesture.Pan()
>     .minDistance(50)
>     .onChange(event => {...
> ```

Thank you for your input. I'm not quite sure to understand. Can you elaborate a bit more on how you achieved this?
Thank you so much
