### ISSUE TITLE
Pan gesture handle onchange callback only support on version 2.2.0+

### ISSUE THREAD

**Issue by nikechanhk** [4TWIGGERS/react-native-fresh-refresh#8]
The onchange callback cannot be found on version 2.1.0
Need to update the package.json to require react-native-gesture-handler at v2.2.0+

**Comment by nikechanhk** [comment]
btw this is a great project!

**Comment by alexandrius** [comment]
Done in 45bd181ba77daef7881b94d881aa1e888c37d973

**Comment by shant1010** [comment]
@alexandrius  Not a bug, and kind of unrelated, but why not support react-native-gesture-handler@^2.8.0? If I force dependencies will this be an issue?
